import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav></nav>
        <main className="main-container flex min-h-screen w-auto flex-col items-start justify-start">
          {children}
        </main>
        <footer className="w-full bg-indigo-950 py-8 text-center text-xs text-white">
          {" "}
          © 2024 Anemora Natura d.o.o.
        </footer>
      </body>
    </html>
  )
}
